confirm_modal.js
bondcoder97/custom_modal pull request #1
Opened 2021-01-22 09:11 UTC by OlgaKhinevich

Hello, I created new file for you)

2021-01-22 10:53 UTC, bondcoder97 commented on confirm_modal.js
> +        modal_wrapper.className = "confirm_modal_wrapper";
Maybe we need to create common class "beauty_modal_wrapper" for both modal types.

2021-01-22 10:54 UTC, bondcoder97 commented on confirm_modal.js
> +        document.body.appendChild(modal_wrapper);
Confirm modal need to return "true" or "false"!

2021-01-22 10:56 UTC, bondcoder97 requested changes
We need to edit some fragments.

2021-01-23 21:26 UTC, OlgaKhinevich commented
Andrusha, I've done all tasks)

2021-01-23 23:05 UTC, bondcoder97 commented
Thanks! :)

2021-01-23 23:05 UTC, merged